/**
 * Content Seeder - Helper script to add sample content for testing recommendations
 * This can be called via API or run directly
 */

import express from 'express';
import Content from '../models/Content.js';

const router = express.Router();

/**
 * POST /api/content/seed
 * Add sample content to database for testing
 */
router.post('/seed', async (req, res) => {
  try {
    const { force } = req.query;
    
    // If force=true, delete existing content
    if (force === 'true') {
      await Content.deleteMany({});
      console.log('Existing content deleted');
    }

    const sampleContent = [
      {
        contentId: 'movie_001',
        title: 'The Dark Knight',
        genre: ['Action', 'Crime', 'Drama'],
        platform: 'Netflix',
        rating: 9.0,
        duration: 152,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        description: 'Batman faces the Joker in this epic crime thriller',
        mood_tags: ['thrilled', 'excited', 'thoughtful'],
        cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
        director: 'Christopher Nolan',
        year: 2008,
      },
      {
        contentId: 'movie_002',
        title: 'Inception',
        genre: ['Action', 'Sci-Fi', 'Thriller'],
        platform: 'Netflix',
        rating: 8.8,
        duration: 148,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
        description: 'A mind-bending sci-fi thriller about dreams within dreams',
        mood_tags: ['curious', 'thrilled', 'thoughtful'],
        cast: ['Leonardo DiCaprio', 'Marion Cotillard', 'Tom Hardy'],
        director: 'Christopher Nolan',
        year: 2010,
      },
      {
        contentId: 'movie_003',
        title: 'The Shawshank Redemption',
        genre: ['Drama'],
        platform: 'Netflix',
        rating: 9.3,
        duration: 142,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        description: 'A story of hope and friendship in prison',
        mood_tags: ['thoughtful', 'melancholic', 'hopeful'],
        cast: ['Tim Robbins', 'Morgan Freeman'],
        director: 'Frank Darabont',
        year: 1994,
      },
      {
        contentId: 'movie_004',
        title: 'Pulp Fiction',
        genre: ['Crime', 'Drama'],
        platform: 'Netflix',
        rating: 8.9,
        duration: 154,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        description: 'A nonlinear crime story with memorable characters',
        mood_tags: ['excited', 'thrilled', 'energetic'],
        cast: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman'],
        director: 'Quentin Tarantino',
        year: 1994,
      },
      {
        contentId: 'movie_005',
        title: 'The Matrix',
        genre: ['Action', 'Sci-Fi'],
        platform: 'Netflix',
        rating: 8.7,
        duration: 136,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        description: 'A computer hacker discovers the truth about reality',
        mood_tags: ['excited', 'curious', 'thrilled'],
        cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
        director: 'Lana Wachowski',
        year: 1999,
      },
      {
        contentId: 'movie_006',
        title: 'Forrest Gump',
        genre: ['Drama', 'Romance'],
        platform: 'Netflix',
        rating: 8.8,
        duration: 142,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1Td2a.jpg',
        description: 'The life story of a simple man with extraordinary experiences',
        mood_tags: ['happy', 'nostalgic', 'thoughtful'],
        cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
        director: 'Robert Zemeckis',
        year: 1994,
      },
      {
        contentId: 'movie_007',
        title: 'The Godfather',
        genre: ['Crime', 'Drama'],
        platform: 'Netflix',
        rating: 9.2,
        duration: 175,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
        description: 'The story of a powerful Italian-American crime family',
        mood_tags: ['thoughtful', 'thrilled', 'melancholic'],
        cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
        director: 'Francis Ford Coppola',
        year: 1972,
      },
      {
        contentId: 'movie_008',
        title: 'Interstellar',
        genre: ['Adventure', 'Drama', 'Sci-Fi'],
        platform: 'Netflix',
        rating: 8.6,
        duration: 169,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        description: 'A team of explorers travel through a wormhole in space',
        mood_tags: ['thoughtful', 'curious', 'melancholic'],
        cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
        director: 'Christopher Nolan',
        year: 2014,
      },
      {
        contentId: 'movie_009',
        title: 'The Avengers',
        genre: ['Action', 'Adventure', 'Sci-Fi'],
        platform: 'Disney+',
        rating: 8.0,
        duration: 143,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
        description: 'Earth\'s mightiest heroes assemble',
        mood_tags: ['excited', 'energetic', 'happy'],
        cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
        director: 'Joss Whedon',
        year: 2012,
      },
      {
        contentId: 'movie_010',
        title: 'Parasite',
        genre: ['Comedy', 'Drama', 'Thriller'],
        platform: 'Netflix',
        rating: 8.5,
        duration: 132,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        description: 'A poor family schemes to become employed by a wealthy family',
        mood_tags: ['thoughtful', 'thrilled', 'curious'],
        cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
        director: 'Bong Joon-ho',
        year: 2019,
      },
      // HAPPY MOOD MOVIES
      {
        contentId: 'movie_011',
        title: 'The Grand Budapest Hotel',
        genre: ['Comedy', 'Drama', 'Adventure'],
        platform: 'Netflix',
        rating: 8.1,
        duration: 99,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/nX5XotM9yprjKgfXH7u4aFEVh3x.jpg',
        description: 'A whimsical comedy about a legendary concierge and his protégé',
        mood_tags: ['happy', 'energetic', 'nostalgic'],
        cast: ['Ralph Fiennes', 'Tony Revolori', 'F. Murray Abraham'],
        director: 'Wes Anderson',
        year: 2014,
      },
      {
        contentId: 'movie_012',
        title: 'La La Land',
        genre: ['Musical', 'Comedy', 'Drama', 'Romance'],
        platform: 'Netflix',
        rating: 8.0,
        duration: 128,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
        description: 'A jazz pianist and an aspiring actress fall in love',
        mood_tags: ['happy', 'romantic', 'energetic'],
        cast: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
        director: 'Damien Chazelle',
        year: 2016,
      },
      {
        contentId: 'movie_013',
        title: 'The Intouchables',
        genre: ['Comedy', 'Drama', 'Biography'],
        platform: 'Netflix',
        rating: 8.5,
        duration: 112,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/4mFsNQwbD0F237Tx7gAPotd0nbJ.jpg',
        description: 'An unlikely friendship between a quadriplegic and his caregiver',
        mood_tags: ['happy', 'thoughtful', 'energetic'],
        cast: ['François Cluzet', 'Omar Sy', 'Anne Le Ny'],
        director: 'Olivier Nakache',
        year: 2011,
      },
      // SAD MOOD MOVIES
      {
        contentId: 'movie_014',
        title: 'The Fault in Our Stars',
        genre: ['Drama', 'Romance'],
        platform: 'Netflix',
        rating: 7.7,
        duration: 126,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/sc6XLX6J714LDkVV4J4VN4dGz0z.jpg',
        description: 'Two teenagers with cancer fall in love',
        mood_tags: ['sad', 'romantic', 'melancholic'],
        cast: ['Shailene Woodley', 'Ansel Elgort', 'Nat Wolff'],
        director: 'Josh Boone',
        year: 2014,
      },
      {
        contentId: 'movie_015',
        title: 'Manchester by the Sea',
        genre: ['Drama'],
        platform: 'Netflix',
        rating: 7.8,
        duration: 137,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/pev79zU4tK4kCXQ1kKd9w9YvFm.jpg',
        description: 'A man returns to his hometown after his brother dies',
        mood_tags: ['sad', 'melancholic', 'thoughtful'],
        cast: ['Casey Affleck', 'Michelle Williams', 'Kyle Chandler'],
        director: 'Kenneth Lonergan',
        year: 2016,
      },
      // RELAXED MOOD MOVIES
      {
        contentId: 'movie_016',
        title: 'The Secret Life of Walter Mitty',
        genre: ['Adventure', 'Comedy', 'Drama'],
        platform: 'Netflix',
        rating: 7.3,
        duration: 114,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/ctjEj2xR32s0l7A3xH11e2Lmb4L.jpg',
        description: 'A daydreamer embarks on a real-life adventure',
        mood_tags: ['relaxed', 'peaceful', 'adventurous'],
        cast: ['Ben Stiller', 'Kristen Wiig', 'Sean Penn'],
        director: 'Ben Stiller',
        year: 2013,
      },
      {
        contentId: 'movie_017',
        title: 'Chef',
        genre: ['Comedy', 'Drama'],
        platform: 'Netflix',
        rating: 7.3,
        duration: 114,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/8T9pdu0ngy6pY9Y2h0N2XvZJz5x.jpg',
        description: 'A chef starts a food truck to reclaim his creative freedom',
        mood_tags: ['relaxed', 'happy', 'peaceful'],
        cast: ['Jon Favreau', 'Sofia Vergara', 'John Leguizamo'],
        director: 'Jon Favreau',
        year: 2014,
      },
      // STRESSED MOOD MOVIES (Light/Comedy to help)
      {
        contentId: 'movie_018',
        title: 'The Hangover',
        genre: ['Comedy'],
        platform: 'Netflix',
        rating: 7.7,
        duration: 100,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/uluhlXubGu1VxU63O9I1iH1W1o2.jpg',
        description: 'Three friends wake up with no memory of the previous night',
        mood_tags: ['happy', 'energetic', 'excited'],
        cast: ['Bradley Cooper', 'Ed Helms', 'Zach Galifianakis'],
        director: 'Todd Phillips',
        year: 2009,
      },
      {
        contentId: 'movie_019',
        title: 'Groundhog Day',
        genre: ['Comedy', 'Fantasy', 'Romance'],
        platform: 'Netflix',
        rating: 8.0,
        duration: 101,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/gCgt1WARPZaXnq523y6eUpl4Q3f.jpg',
        description: 'A weatherman gets stuck in a time loop',
        mood_tags: ['happy', 'thoughtful', 'romantic'],
        cast: ['Bill Murray', 'Andie MacDowell', 'Chris Elliott'],
        director: 'Harold Ramis',
        year: 1993,
      },
      // BORED MOOD MOVIES (Action/Thriller)
      {
        contentId: 'movie_020',
        title: 'John Wick',
        genre: ['Action', 'Crime', 'Thriller'],
        platform: 'Netflix',
        rating: 7.4,
        duration: 101,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
        description: 'An ex-hitman seeks vengeance',
        mood_tags: ['excited', 'energetic', 'thrilled'],
        cast: ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen'],
        director: 'Chad Stahelski',
        year: 2014,
      },
      {
        contentId: 'movie_021',
        title: 'Mad Max: Fury Road',
        genre: ['Action', 'Adventure', 'Sci-Fi'],
        platform: 'Netflix',
        rating: 8.1,
        duration: 120,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/hA2ple9q4mBRG3rg6GB3Z3Q6w0.jpg',
        description: 'A post-apocalyptic action thriller',
        mood_tags: ['excited', 'energetic', 'thrilled'],
        cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
        director: 'George Miller',
        year: 2015,
      },
      // ROMANTIC MOOD MOVIES
      {
        contentId: 'movie_022',
        title: 'The Notebook',
        genre: ['Drama', 'Romance'],
        platform: 'Netflix',
        rating: 7.8,
        duration: 123,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/rNzQyW4f8B8c1eg7T7n5iIyv5hq.jpg',
        description: 'A love story that spans decades',
        mood_tags: ['romantic', 'nostalgic', 'melancholic'],
        cast: ['Ryan Gosling', 'Rachel McAdams', 'James Garner'],
        director: 'Nick Cassavetes',
        year: 2004,
      },
      {
        contentId: 'movie_023',
        title: 'Pride and Prejudice',
        genre: ['Drama', 'Romance'],
        platform: 'Netflix',
        rating: 7.8,
        duration: 129,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/5fLJj3qkyX7XlGf1WAK8qZqJz7x.jpg',
        description: 'Elizabeth Bennet and Mr. Darcy navigate love and social class',
        mood_tags: ['romantic', 'nostalgic', 'thoughtful'],
        cast: ['Keira Knightley', 'Matthew Macfadyen', 'Brenda Blethyn'],
        director: 'Joe Wright',
        year: 2005,
      },
      // ADVENTUROUS MOOD MOVIES
      {
        contentId: 'movie_024',
        title: 'Indiana Jones: Raiders of the Lost Ark',
        genre: ['Action', 'Adventure'],
        platform: 'Disney+',
        rating: 8.4,
        duration: 115,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/ceG9VzoBRVG3ibrL7xBUfa8z3hN.jpg',
        description: 'An archaeologist races against Nazis to find the Ark of the Covenant',
        mood_tags: ['adventurous', 'excited', 'energetic'],
        cast: ['Harrison Ford', 'Karen Allen', 'Paul Freeman'],
        director: 'Steven Spielberg',
        year: 1981,
      },
      {
        contentId: 'movie_025',
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        genre: ['Adventure', 'Drama', 'Fantasy'],
        platform: 'HBO Max',
        rating: 8.8,
        duration: 178,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnJk2p1xq.jpg',
        description: 'A hobbit embarks on a quest to destroy a powerful ring',
        mood_tags: ['adventurous', 'excited', 'thoughtful'],
        cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
        director: 'Peter Jackson',
        year: 2001,
      },
      // THOUGHTFUL MOOD MOVIES
      {
        contentId: 'movie_026',
        title: '12 Angry Men',
        genre: ['Drama', 'Crime'],
        platform: 'Netflix',
        rating: 9.0,
        duration: 96,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/3W0v956XxSG5xgm7lb6msW1g3cL.jpg',
        description: 'A jury deliberates a murder case',
        mood_tags: ['thoughtful', 'curious', 'peaceful'],
        cast: ['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'],
        director: 'Sidney Lumet',
        year: 1957,
      },
      {
        contentId: 'movie_027',
        title: 'The Social Network',
        genre: ['Biography', 'Drama'],
        platform: 'Netflix',
        rating: 7.7,
        duration: 120,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/ok5Wh8385Kgblq9MSU4VGvazeMH.jpg',
        description: 'The story of Facebook\'s creation',
        mood_tags: ['thoughtful', 'curious', 'energetic'],
        cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'],
        director: 'David Fincher',
        year: 2010,
      },
      // ENERGETIC MOOD MOVIES
      {
        contentId: 'movie_028',
        title: 'Baby Driver',
        genre: ['Action', 'Crime', 'Drama'],
        platform: 'Netflix',
        rating: 7.6,
        duration: 113,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/rmnQ9jqN1wX1x13nFxh5i3zH5t.jpg',
        description: 'A young getaway driver gets caught in a heist gone wrong',
        mood_tags: ['energetic', 'excited', 'thrilled'],
        cast: ['Ansel Elgort', 'Kevin Spacey', 'Lily James'],
        director: 'Edgar Wright',
        year: 2017,
      },
      {
        contentId: 'movie_029',
        title: 'Whiplash',
        genre: ['Drama', 'Music'],
        platform: 'Netflix',
        rating: 8.5,
        duration: 107,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/7fn624l5V3v16MCPg4R5cIdUcPw.jpg',
        description: 'A young drummer pursues perfection under a ruthless instructor',
        mood_tags: ['energetic', 'excited', 'thoughtful'],
        cast: ['Miles Teller', 'J.K. Simmons', 'Paul Reiser'],
        director: 'Damien Chazelle',
        year: 2014,
      },
      // MELANCHOLIC MOOD MOVIES
      {
        contentId: 'movie_030',
        title: 'Her',
        genre: ['Drama', 'Romance', 'Sci-Fi'],
        platform: 'Netflix',
        rating: 8.0,
        duration: 126,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/yk4J4aewWDTdQ69v2KG9g7Qz3.jpg',
        description: 'A man falls in love with an AI operating system',
        mood_tags: ['melancholic', 'thoughtful', 'romantic'],
        cast: ['Joaquin Phoenix', 'Scarlett Johansson', 'Amy Adams'],
        director: 'Spike Jonze',
        year: 2013,
      },
      {
        contentId: 'movie_031',
        title: 'Lost in Translation',
        genre: ['Drama', 'Romance'],
        platform: 'Netflix',
        rating: 7.7,
        duration: 102,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/4k8vWX1hX7R9Q1F7Q9x9X9X9X9X.jpg',
        description: 'Two lost souls form an unlikely bond in Tokyo',
        mood_tags: ['melancholic', 'peaceful', 'thoughtful'],
        cast: ['Bill Murray', 'Scarlett Johansson', 'Giovanni Ribisi'],
        director: 'Sofia Coppola',
        year: 2003,
      },
      // NOSTALGIC MOOD MOVIES
      {
        contentId: 'movie_032',
        title: 'The Princess Bride',
        genre: ['Adventure', 'Comedy', 'Family', 'Fantasy', 'Romance'],
        platform: 'Disney+',
        rating: 8.1,
        duration: 98,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/9BTDNgZ73a9YfzMf1Bt3csa2Wfa.jpg',
        description: 'A classic fairy tale adventure',
        mood_tags: ['nostalgic', 'happy', 'romantic'],
        cast: ['Cary Elwes', 'Robin Wright', 'Mandy Patinkin'],
        director: 'Rob Reiner',
        year: 1987,
      },
      {
        contentId: 'movie_033',
        title: 'Back to the Future',
        genre: ['Adventure', 'Comedy', 'Sci-Fi'],
        platform: 'Netflix',
        rating: 8.5,
        duration: 116,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOxjJdZ3qS.jpg',
        description: 'A teenager travels back in time to 1955',
        mood_tags: ['nostalgic', 'happy', 'excited'],
        cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
        director: 'Robert Zemeckis',
        year: 1985,
      },
      // THRILLED MOOD MOVIES
      {
        contentId: 'movie_034',
        title: 'Se7en',
        genre: ['Crime', 'Drama', 'Mystery', 'Thriller'],
        platform: 'Netflix',
        rating: 8.6,
        duration: 127,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg',
        description: 'Two detectives hunt a serial killer',
        mood_tags: ['thrilled', 'curious', 'thoughtful'],
        cast: ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow'],
        director: 'David Fincher',
        year: 1995,
      },
      {
        contentId: 'movie_035',
        title: 'Gone Girl',
        genre: ['Drama', 'Mystery', 'Thriller'],
        platform: 'Netflix',
        rating: 8.1,
        duration: 149,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/gdiLTof3rbPDAmPaCf4g6op46bj.jpg',
        description: 'A man becomes the prime suspect when his wife disappears',
        mood_tags: ['thrilled', 'curious', 'thoughtful'],
        cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'],
        director: 'David Fincher',
        year: 2014,
      },
      // PEACEFUL MOOD MOVIES
      {
        contentId: 'movie_036',
        title: 'The Tree of Life',
        genre: ['Drama', 'Fantasy'],
        platform: 'Netflix',
        rating: 6.8,
        duration: 139,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/rnd0tq2E8L5q8v0t5Q5f5f5f5f5.jpg',
        description: 'A poetic meditation on life, nature, and existence',
        mood_tags: ['peaceful', 'thoughtful', 'nostalgic'],
        cast: ['Brad Pitt', 'Sean Penn', 'Jessica Chastain'],
        director: 'Terrence Malick',
        year: 2011,
      },
      {
        contentId: 'movie_037',
        title: 'My Neighbor Totoro',
        genre: ['Animation', 'Family', 'Fantasy'],
        platform: 'Netflix',
        rating: 8.2,
        duration: 86,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/rtGDOeG9L0er0dHm8g3J2Z0f9B0.jpg',
        description: 'Two sisters befriend forest spirits',
        mood_tags: ['peaceful', 'happy', 'nostalgic'],
        cast: ['Hitoshi Takagi', 'Noriko Hidaka', 'Chika Sakamoto'],
        director: 'Hayao Miyazaki',
        year: 1988,
      },
      // CURIOUS MOOD MOVIES
      {
        contentId: 'movie_038',
        title: 'Arrival',
        genre: ['Drama', 'Sci-Fi', 'Thriller'],
        platform: 'Netflix',
        rating: 7.9,
        duration: 116,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/hLudzvGfyi6iq1r2z4dbj3X5x3j.jpg',
        description: 'A linguist works to communicate with alien visitors',
        mood_tags: ['curious', 'thoughtful', 'peaceful'],
        cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
        director: 'Denis Villeneuve',
        year: 2016,
      },
      {
        contentId: 'movie_039',
        title: 'Ex Machina',
        genre: ['Drama', 'Sci-Fi', 'Thriller'],
        platform: 'Netflix',
        rating: 7.7,
        duration: 108,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/btbRB7BrG8h4V2sJf2Z5q3N3p3N.jpg',
        description: 'A programmer is invited to test an AI\'s consciousness',
        mood_tags: ['curious', 'thoughtful', 'thrilled'],
        cast: ['Domhnall Gleeson', 'Alicia Vikander', 'Oscar Isaac'],
        director: 'Alex Garland',
        year: 2014,
      },
      {
        contentId: 'movie_040',
        title: 'Blade Runner 2049',
        genre: ['Action', 'Drama', 'Sci-Fi', 'Thriller'],
        platform: 'Netflix',
        rating: 8.0,
        duration: 164,
        thumbnailUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlbJUYun5B.jpg',
        description: 'A young blade runner discovers a secret',
        mood_tags: ['curious', 'thoughtful', 'thrilled'],
        cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
        director: 'Denis Villeneuve',
        year: 2017,
      },
    ];

    // Check if content already exists (only if not forcing)
    if (force !== 'true') {
      const existingCount = await Content.countDocuments();
      if (existingCount > 0) {
        return res.status(200).json({
          success: true,
          message: `Database already has ${existingCount} content items. Use POST /api/content/seed?force=true to replace.`,
          count: existingCount,
        });
      }
    }

    // Insert sample content
    const inserted = await Content.insertMany(sampleContent);

    res.status(201).json({
      success: true,
      message: `Successfully added ${inserted.length} sample content items`,
      count: inserted.length,
    });
  } catch (error) {
    console.error('Content seeder error:', error);
    res.status(500).json({
      success: false,
      error: error.message || 'Failed to seed content',
    });
  }
});

/**
 * GET /api/content/count
 * Get count of content in database
 */
router.get('/count', async (req, res) => {
  try {
    const count = await Content.countDocuments();
    res.status(200).json({
      success: true,
      count,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error.message || 'Failed to get content count',
    });
  }
});

export default router;

